apiVersion: apps/v1
kind: Deployment
metadata:
  name: FSEDocker-deployment
  labels:
    app: FSEDocker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: FSEDocker  
  template:
    metadata:
      labels:
        app: FSEDocker
    spec:
      containers:
      - name: myazurecr008
        image: myazurecr008.azurecr.io/azurecontainerrepo2:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: webapisvcsecret
---
apiVersion: v1
kind: Service
metadata:
  name: FSEDockersvc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: FSEDocker